function t410_init(recid){var el=$('#rec'+recid);var firstimgurl=el.find(".t410__wrapper").attr("data-juxtapose-imgurl-first");var firstimgdescr=el.find(".t410__wrapper").attr("data-juxtapose-imgdescr-first");var firstimgalt=el.find(".t410__wrapper").attr("data-juxtapose-imgalt-first");var secondimgurl=el.find(".t410__wrapper").attr("data-juxtapose-imgurl-second");var secondimgdescr=el.find(".t410__wrapper").attr("data-juxtapose-imgdescr-second");var secondimgalt=el.find(".t410__wrapper").attr("data-juxtapose-imgalt-second");new juxtapose.JXSlider('#t410-juxtapose__'+recid,[{src:firstimgurl,label:firstimgdescr},{src:secondimgurl,label:secondimgdescr}],{animate:!1,showLabels:!0,showCredits:!1,startingPosition:'50%',makeResponsive:!0,callback:function(){if(firstimgalt.length>0){el.find('.t410__wrapper .jx-image.jx-left img').attr('alt',firstimgalt)}
if(secondimgalt.length>0){el.find('.t410__wrapper .jx-image.jx-right img').attr('alt',secondimgalt)}
if(window.$isMobile){el.find('.t410__wrapper').append('<div class="t410__mobile_left"></div><div class="t410__mobile_right"></div>');var hanlerWidth=el.find('.jx-handle').width(),leftSide=el.find('.jx-image.jx-left'),rightSide=el.find('.jx-image.jx-right'),leftWidth=leftSide.width()-hanlerWidth/2,rightWidth=rightSide.width()-hanlerWidth/2,wrapper=el.find('.t410__wrapper'),mobileLeft=el.find('.t410__mobile_left'),mobileRight=el.find('.t410__mobile_right');mobileLeft.css('width',leftWidth);mobileRight.css('width',rightWidth);wrapper.on('touchend',function(){leftWidth=leftSide.width()-hanlerWidth/2;rightWidth=rightSide.width()-hanlerWidth/2;mobileLeft.css('width',leftWidth);mobileRight.css('width',rightWidth)})}}});el.find('.t410').bind('displayChanged',function(){window.juxtapose.sliders.forEach(function(obj){if(obj.selector==='#t410-juxtapose__'+recid){console.log(obj);obj.setWrapperDimensions();return}})})}
function t657_init(recid){var t657_el=$('#rec'+recid),t657_block=t657_el.find('.t657'),t657_closeBtn=t657_el.find('.t657__btn'),t657_closeIcon=t657_el.find('.t657__icon-close'),t657_storageItem=t657_block.attr('data-storage-item'),t657_lastOpen=localStorage.getItem(t657_storageItem);if(t657_lastOpen==null){t657_block.removeClass('t657_closed')}
t657_closeBtn.add(t657_closeIcon).click(function(e){t657_block.addClass('t657_closed');localStorage.setItem(t657_storageItem,Math.floor(Date.now()/1000));e.preventDefault()})}
function t694_init(recid){var el=$('#rec'+recid);t694_setHeight(recid);$(window).resize(t_throttle(function(){t694_setHeight(recid)}));el.find('.t694').bind('displayChanged',t_throttle(function(){t694_setHeight(recid)}))}
function t694_setHeight(recid){var el=$('#rec'+recid+' .t694');var t694_ratio=el.attr('data-tile-ratio');var t694_ratioHeight=el.find('.t694__col').width()*t694_ratio;if($(window).width()>=768){el.find('.t694__row').each(function(){var t694_largestHeight=0,t694_currow=$(this);$('.t694__table',this).each(function(){var t694_curCol=$(this),t694_curColHeight=t694_curCol.find(".t694__textwrapper").outerHeight();if($(this).find(".t694__cell").hasClass("t694__button-bottom")){t694_curColHeight+=t694_curCol.find(".t694__button-container").outerHeight()}
if(t694_curColHeight>t694_largestHeight){t694_largestHeight=t694_curColHeight}});if(t694_largestHeight>t694_ratioHeight){$('.t694__table',this).css('height',t694_largestHeight)}else{if($('.t694__table',this).css('height')!=''){$('.t694__table',this).css('height','')}}})}else{el.find('.t694__table').css('height','')}}
function t796_init(recid){var el=$("#rec"+recid);var shapeEl=el.find(".t796__shape-border");var recs=el.find(".t796").attr("data-shape-rec-ids");if(typeof recs!="undefined"){recs=recs.split(",");recs.forEach(function(rec_id,i,arr){var curRec=$("#rec"+rec_id);var curShapeEl=shapeEl.clone();t796_setColor(el,curShapeEl);t796_addDivider(curRec,curShapeEl)})}else{var excludes="[data-record-type='215'],[data-record-type='706'],[data-record-type='651'],[data-record-type='825'],[data-record-type='708']";if(shapeEl.hasClass('t796__shape-border_top')||shapeEl.hasClass('t796__shape-border_top-flip')){var curRec=el.next(".r");if(curRec.is(excludes)){curRec=curRec.next(".r")}}
if(shapeEl.hasClass('t796__shape-border_bottom')||shapeEl.hasClass('t796__shape-border_bottom-flip')){var curRec=el.prev(".r");if(curRec.is(excludes)){curRec=curRec.prev(".r")}}
if(curRec.length!=0){var curShapeEl=shapeEl.clone();t796_setColor(el,curShapeEl);t796_addDivider(curRec,curShapeEl)}}}
function t796_addDivider(curRec,curShapeEl){curRec.attr("data-animationappear","off").removeClass('r_hidden');var coverWrapper=curRec.find(".t-cover");var zeroWrapper=curRec.find(".t396");if(coverWrapper.length>0||zeroWrapper.length>0){if(coverWrapper.length>0){coverWrapper.find(".t-cover__filter").after(curShapeEl)}
if(zeroWrapper.length>0){zeroWrapper.after(curShapeEl);curRec.css("position","relative")}
curShapeEl.css("display","block")}else{var wrapper=curRec;var curRecType=curRec.attr("data-record-type");if(wrapper.length==0){return!0}
wrapper.append(curShapeEl);wrapper.css("position","relative");if(curRecType!="554"&&curRecType!="125"){wrapper.children("div").first().css({"position":"relative","z-index":"1"}).addClass("t796_cont-near-shape-divider")}
if(curRecType=="734"||curRecType=="675"||curRecType=="279"||curRecType=="694"||curRecType=="195"){curShapeEl.css("z-index","1")}
curShapeEl.css("display","block")}}
function t796_setColor(el,curShapeEl){if(typeof curShapeEl.attr("data-fill-color")!="undefined"){return}
if(curShapeEl.hasClass("t796__shape-border_bottom")||curShapeEl.hasClass("t796__shape-border_bottom-flip")){var nearestBlock=el.next(".r")}else{var nearestBlock=el.prev(".r")}
if(nearestBlock.length==0){return}
var fillColor=nearestBlock.attr("data-bg-color");if(typeof fillColor=="undefined"){return}
curShapeEl.find(".t796__svg").css("fill",fillColor)}
function t815_init(recid){var rec=$('#rec'+recid);var el=rec.find('.t815');var isFixed=(el.css('position')=='fixed');var redactorMode=el.hasClass('t815_redactor-mode');if(!redactorMode){el.removeClass('t815__beforeready');if(isFixed&&el.attr('data-bgopacity-two')){t815_changebgopacitymenu(recid);$(window).bind('scroll',t_throttle(function(){t815_changebgopacitymenu(recid)},200))}
if(isFixed&&el.attr('data-appearoffset')){el.removeClass('t815__beforeready');t815_appearMenu(recid);$(window).bind('scroll',t_throttle(function(){t815_appearMenu(recid)},200))}}
t815_setBg(recid);$(window).bind('resize',t_throttle(function(){t815_setBg(recid)},200))}
function t815_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t815").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t815").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t815_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t815").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t815_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t815").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t908_init(recid){var rec=$('#rec'+recid);var item=rec.find('.t908__item');var imageContainer=rec.find('.t908__box-img');rec.find('.t908__item').first().addClass('t908__item_active');rec.find('.t908__box-img').first().addClass('t908__box-img_active');t908_changeActiveTab(item,imageContainer)}
function t908_changeActiveTab(item,imageContainer){var itemNumber;item.on('click',function(e){itemNumber=$(this).attr('data-item-number');imageContainer.removeClass('t908__box-img_active');item.removeClass('t908__item_active');$(this).addClass('t908__item_active');imageContainer.each(function(i){if($(imageContainer[i]).attr('data-item-content-number')===itemNumber){$(imageContainer[i]).addClass('t908__box-img_active')}});if(typeof $('.t-records').attr('data-tilda-mode')==='undefined'){if(window.lazy==='y'){t_lazyload_update()}}})}